### ISSUE TITLE
show/sync fail

### ISSUE THREAD

**Issue by petar** [social4git/social4git#21]
I am trying to run it and running into this:

post and follow work fine, but sync / show fail. 

` 
MacBook-Pro-2:~ vipulprakash$ social4git show
repository not found
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x64
[github.com/gov4git/lib4git/must.mkErr](http://github.com/gov4git/lib4git/must.mkErr)(...)
	/Users/vipulprakash/go/pkg/mod/[github.com/gov4git/lib4git@v0.0.9/must/must.go:16](http://github.com/gov4git/lib4git@v0.0.9/must/must.go:16)
[github.com/gov4git/lib4git/must.Panic](http://github.com/gov4git/lib4git/must.Panic)(...)
	/Users/vipulprakash/go/pkg/mod/[github.com/gov4git/lib4git@v0.0.9/must/must.go:20](http://github.com/gov4git/lib4git@v0.0.9/must/must.go:20)
[github.com/gov4git/lib4git/must.Errorf](http://github.com/gov4git/lib4git/must.Errorf)({0x104f59cc0, 0x1400022e3c0}, {0x104d51b67?, 0x140001d9610?}, {0x140001d95e8?, 0x104f5da28?, 0x1a?})
	/Users/vipulprakash/go/pkg/mod/[github.com/gov4git/lib4git@v0.0.9/must/must.go:24](http://github.com/gov4git/lib4git@v0.0.9/must/must.go:24) +0x50
[github.com/gov4git/lib4git/must.Assertf](http://github.com/gov4git/lib4git/must.Assertf)(...)
	/Users/vipulprakash/go/pkg/mod/[github.com/gov4git/lib4git@v0.0.9/must/must.go:31](http://github.com/gov4git/lib4git@v0.0.9/must/must.go:31)
[github.com/gov4git/lib4git/git.PullOnce](http://github.com/gov4git/lib4git/git.PullOnce)({0x104f59cc0, 0x1400022e3c0}, 0x1400022f050, {0x140001b6500, 0x35}, {0x140002170d0, 0x1, 0x1})
	/Users/vipulprakash/go/pkg/mod/[github.com/gov4git/lib4git@v0.0.9/git/sync.go:135](http://github.com/gov4git/lib4git@v0.0.9/git/sync.go:135) +0x2d4
[github.com/gov4git/lib4git/git](http://github.com/gov4git/lib4git/git).(*clonedCacheProxy).pull(0x14000244600, {0x104f59cc0, 0x1400022e3c0})
	/Users/vipulprakash/go/pkg/mod/[github.com/gov4git/lib4git@v0.0.9/git/cache.go:147](http://github.com/gov4git/lib4git@v0.0.9/git/cache.go:147) +0x144
[github.com/gov4git/lib4git/git](http://github.com/gov4git/lib4git/git).(*Cache).clone(0x140001b5ba0, {0x104f59cc0, 0x1400022e3c0}, {{0x140001b6500?, 0x140001b5ba0?}, {0x104d52f6d?, 0x1052fe9e0?}}, 0x0)
	/Users/vipulprakash/go/pkg/mod/[github.com/gov4git/lib4git@v0.0.9/git/cache.go:77](http://github.com/gov4git/lib4git@v0.0.9/git/cache.go:77) +0x188
[github.com/gov4git/lib4git/git](http://github.com/gov4git/lib4git/git).(*Cache).CloneOne(0xf000?, {0x104f59cc0?, 0x1400022e3c0?}, {{0x140001b6500?, 0x1056a0a68?}, {0x104d52f6d?, 0x140001d9888?}})
	/Users/vipulprakash/go/pkg/mod/[github.com/gov4git/lib4git@v0.0.9/git/cache.go:57](http://github.com/gov4git/lib4git@v0.0.9/git/cache.go:57) +0x30
[github.com/gov4git/lib4git/git.CloneOne](http://github.com/gov4git/lib4git/git.CloneOne)({0x104f59cc0, 0x1400022e3c0}, {{0x140001b6500?, 0x140001d9918?}, {0x104d52f6d?, 0x1052cf0a0?}})
	/Users/vipulprakash/go/pkg/mod/[github.com/gov4git/lib4git@v0.0.9/git/clone.go:33](http://github.com/gov4git/lib4git@v0.0.9/git/clone.go:33) +0x64
[github.com/social4git/social4git/proto.FetchFollowedPostsMonth](http://github.com/social4git/social4git/proto.FetchFollowedPostsMonth)({0x104f59cc0, 0x1400022e3c0}, {{{0x140001b6480, 0x5}, {0x140001b6488, 0xa}, {0x140001e1290, 0x25}}, {0x140001b64c0, 0x37}, ...}, ...)
	/Users/vipulprakash/go/pkg/mod/[github.com/social4git/social4git@v0.0.5/proto/show_followed.go:151](http://github.com/social4git/social4git@v0.0.5/proto/show_followed.go:151) +0x90
[github.com/social4git/social4git/proto.FetchFollowedLatestPostsMonth](http://github.com/social4git/social4git/proto.FetchFollowedLatestPostsMonth)({0x104f59cc0, 0x1400022e3c0}, {{{0x140001b6480, 0x5}, {0x140001b6488, 0xa}, {0x140001e1290, 0x25}}, {0x140001b64c0, 0x37}, ...})
	/Users/vipulprakash/go/pkg/mod/[github.com/social4git/social4git@v0.0.5/proto/show_followed_latest.go:19](http://github.com/social4git/social4git@v0.0.5/proto/show_followed_latest.go:19) +0xd4
[github.com/social4git/social4git/social4git/cmd.glob..func7](http://github.com/social4git/social4git/social4git/cmd.glob..func7)(0x1052c7b40?, {0x104d52121?, 0x0?, 0x0?})
	/Users/vipulprakash/go/pkg/mod/[github.com/social4git/social4git@v0.0.5/social4git/cmd/show.go:55](http://github.com/social4git/social4git@v0.0.5/social4git/cmd/show.go:55) +0x308
[github.com/spf13/cobra](http://github.com/spf13/cobra).(*Command).execute(0x1052c7b40, {0x1052feb80, 0x0, 0x0})
	/Users/vipulprakash/go/pkg/mod/[github.com/spf13/cobra@v1.6.1/command.go:920](http://github.com/spf13/cobra@v1.6.1/command.go:920) +0x5b0
[github.com/spf13/cobra](http://github.com/spf13/cobra).(*Command).ExecuteC(0x1052c6ce0)
	/Users/vipulprakash/go/pkg/mod/[github.com/spf13/cobra@v1.6.1/command.go:1044](http://github.com/spf13/cobra@v1.6.1/command.go:1044) +0x35c
[github.com/spf13/cobra](http://github.com/spf13/cobra).(*Command).Execute(...)
	/Users/vipulprakash/go/pkg/mod/[github.com/spf13/cobra@v1.6.1/command.go:968](http://github.com/spf13/cobra@v1.6.1/command.go:968)
[github.com/social4git/social4git/social4git/cmd.Execute](http://github.com/social4git/social4git/social4git/cmd.Execute)()
	/Users/vipulprakash/go/pkg/mod/[github.com/social4git/social4git@v0.0.5/social4git/cmd/root.go:88](http://github.com/social4git/social4git@v0.0.5/social4git/cmd/root.go:88) +0x28
main.main()
	/Users/vipulprakash/go/pkg/mod/[github.com/social4git/social4git@v0.0.5/social4git/main.go:22](http://github.com/social4git/social4git@v0.0.5/social4git/main.go:22) +0x38
`

**Comment by petar** [comment]
i discovered that following a non-existent but valid repo URL can return `authentication required`, `i/o timeout`, `repository not found`.
